package com.poloniex.api.client.model.request;

import lombok.Builder;
import lombok.Data;

/**
 * Auth params required to establish authenticated subscription
 */
@Data
@Builder
public class AuthParams {

    /**
     * entry whose value is api caller’s apiKey. e.g. “A…-99…”
     */
    private String key;

    /**
     * entry whose value is a timestamp. e.g. “1649371360000“
     */
    private Long signTimestamp;

    /**
     * entry whose value is the signature generated by API caller for the request. e.g. “4F…%3D”
     */
    private String signature;
}
