package com.poloniex.api.client.spot.common;

/**
 * Candlestick channels
 */
public enum CandlestickChannels {
    CANDLES_MINUTE_1, CANDLES_MINUTE_5, CANDLES_MINUTE_10, CANDLES_MINUTE_15, CANDLES_MINUTE_30, CANDLES_HOUR_1, CANDLES_HOUR_2, CANDLES_HOUR_4, CANDLES_HOUR_6, CANDLES_HOUR_12, CANDLES_DAY_1, CANDLES_DAY_3, CANDLES_WEEK_1, CANDLES_MONTH_1
}
